<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\AudiA6.jpg" />
    <None Remove="Resources\Icon.ico" />
    <None Remove="Resources\ph.jpg" />
    <None Remove="Resources\ph2.jpg" />
    <None Remove="Resources\ph3.jpg" />
    <None Remove="Resources\ph4.jpg" />
    <None Remove="Resources\ph5.jpg" />
    <None Remove="Resources\ph6.jpg" />
    <None Remove="Resources\ph7.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Styles\DataGrid.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\ph4.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dragablz" Version="0.0.3.223" />
    <PackageReference Include="MaterialDesignExtensions" Version="3.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentalCarApplication.Core\RentalCarApplication.Core.csproj" />
    <ProjectReference Include="..\RentalCarApplication.EntityFramework\RentalCarApplication.EntityFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="emailsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>CopyAlways</CopyToOutputDirectory>
    </None>
    <Resource Include="Resources\Icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ph.jpg" />
    <Resource Include="Resources\ph2.jpg" />
    <Resource Include="Resources\ph3.jpg" />
    <Resource Include="Resources\ph5.jpg" />
    <Resource Include="Resources\ph6.jpg" />
    <Resource Include="Resources\ph7.jpg" />
    <Resource Include="Styles\DataGrid.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>
</Project>
